### ISSUE TITLE
Jest + jsdom + Vite test environment failing to run

### ISSUE THREAD

**Issue by spencerlepine** [Blue-Ocean-Team-1/HelloHealth#6]
🔵 See branch: [jest-test-bug](https://github.com/Blue-Ocean-Team-1/HelloHealth/tree/jest-test-bug)
🔵 Ticket: [Trello Ticket](https://trello.com/c/LNVTLuD1/43-jest-dom-jsx-testing-enviroment-setup)

## Ideas:
- tested without `import.meta` and use hard-coded environment variables (config.js) 
  - **RESULT:**: test were able to pass. Only tests fail when `import.meta` is used
- Run `node --experimental-modules`?
  
## Context:
- Jest/node tests run fine (*.test.js in /server folder)
- Jest/jsdom test cannot run (*.test.js in client folder)
- Jest and jsdom must use babel to understand the jsx (eg `render(<App />)`)
- VITE in the client must use `import.meta.env` instead of `process.env`
- Jest does not like this `import.meta.env` import 

## Steps to Reproduce:

1. Have these files in the Repository:
```js
// <rootDir>/jest.config.js
module.exports = {
  projects: [
    {
      displayName: 'dom',
      testEnvironment: 'jsdom',
      // "extensionsToTreatAsEsm": [".jsx"],
      testMatch: [
        '<rootDir>/client/**/*.test.js?(x)',
      ],
    },
    {
      displayName: 'node',
      testEnvironment: 'node',
      testMatch: [
        '<rootDir>/server/**/*.test.js?(x)',
      ],
    },
  ],
};
```
```js
// <rootDir>/client/test-utils/index.js
import React from 'react';
import { render } from '@testing-library/react';
import { MainProvider } from '../src/context/MainContext.jsx';
import { AuthProvider } from '../src/context/AuthContext.jsx';

const AllProviders = ({ children }) => (
  <MainProvider>
    <AuthProvider>
      {children}
    </AuthProvider>
  </MainProvider>
);

const customRender = (ui, options) => (
  render(ui, { wrapper: AllProviders, ...options })
);

export * from '@testing-library/react';

export { customRender as render };

```
```js
// <rootDir>/client/src/components/App.test.js
import React from 'react';
import App from './App.jsx';
import {
  render,
  screen,
  fireEvent,
  getByLabelText,
} from '../../test-utils';

describe('<App />', () => {
  beforeEach(() => {
    render(<App />);
  });

  it('then shows the light theme by default', () => {
    expect(screen.getByText(/HelloHealth/i)).toBeTruthy();
  });
});
```

2. run this command:
`npx jest ./client/src/components/App.test.js`

---
![Screen Shot 2021-10-16 at 3 49 41 PM](https://user-images.githubusercontent.com/60903378/137603916-dd83dd96-3056-4b1b-b0da-897ece0e4687.png)

# Terminal Output:
```sh
 FAIL   dom  client/src/components/Pages/LoginPage/LoginPage.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/notspencer/Documents/Hack Reactor/SEI/HelloHealth/client/src/config/config.js:32
    }).validate(import.meta.env),
                       ^^^^

    SyntaxError: Cannot use 'import.meta' outside a module

      2 | import 'firebase/auth';
      3 | import 'firebase/firestore';
    > 4 | import config from './config';
        | ^
      5 |
      6 | const app = firebase.initializeApp(config.firebaseConfig);
      7 | export default app;

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1723:14)
      at Object.<anonymous> (client/src/config/firebase.js:4:1)
```

**Comment by spencerlepine** [comment]
Trying this: https://stackoverflow.com/a/68783473

**Comment by spencerlepine** [comment]
# VITE enviroment variables

### Explanation:
With a `.env` file in the project root directory:
VITE does not process the environment variables the same way React does. You cannot use `process.env` by default.
`import.meta.env` seemed to be working instead.
However, jest + jest-dom test's were failling.

## Solution:
Use a library to add process.env functionality to the Vite project and jest enviroment.

1. Install [babel-preset-vite](https://www.npmjs.com/package/babel-preset-vite)
`npm install --save-dev babel-preset-vite`

2. update the `.babelrc` file:
```
{
  ...
  "presets": [
    [
      "babel-preset-vite",
      {
        "env": true, // defaults to true
        "glob": false // defaults to true
      }
    ]
  ]
}
```

3. Use `process.env` (NOT `import.meta`)
```js
import dotenv from 'dotenv';

dotenv.config();

const enviromentObj = process.env;
```
